
name: Update Chromedriver to Stable

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  schedule_chromedriver:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests
      - run: |
          python actionUpdater.py chromedriver
      - name: Upload to nemo
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "test@travelctm.com"
          git status
          git add .
          git commit -m "Updated chromedriver"
          git push
      
